apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::186759254855:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-MOHA1UQ6GY9T
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-08T20:36:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1583"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ad224ce1-aa19-4640-a4ed-5c7ba338c85b
